version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapeie a porta do contêiner para uma porta no host

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_julius
    ports:
      - "5432:5432"  # Mapeie a porta do contêiner para uma porta no host
