version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapeie a porta do contêiner para uma porta no host

  database:
    image: postgres:latest
    ports:
      - "5433:5433"  # Mapeie a porta do contêiner para uma porta no host
    environment:
      POSTGRES_PASSWORD: root
